development:
  adapter: postgresql
  database: stack_development

test:
  adapter: postgresql
  database: stack_test

production:
  adapter: postgresql
  encoding: unicode
  database: stack_production